feat(nextjs): Add performance monitoring support to scripts
getsentry/sentry-wizard pull request #114
Opened 2021-05-28 09:41 UTC by iker-barriocanal

Setting `tracesSampleRate` is key for performance monitoring. This PR adds it to the two files (`sentry.client.config.js` and `sentry.server.config.js`) initializing the Next.js SDK.

2021-05-28 19:20 UTC, rhcarvalho commented on scripts/NextJs/configs/sentry.client.config.js
> +  // for finer control
I think we could try to find a terser comment that delivers the same message.
There's already too much to read, and people tend to ignore walls of text.

```suggestion
    // Adjust this value in production, or use tracesSampler for greater control
```

2021-05-31 07:46 UTC, iker-barriocanal commented on scripts/NextJs/configs/sentry.client.config.js
> +  tracesSampleRate: 1.0,
It depends on where you look at, in some places the value is `1.0` ([example](https://docs.sentry.io/platforms/javascript/#configure)). My thought here is that users who are using performance monitoring for the first time (or haven't used it much before) aren't going to use it directly in production, so seeing all transactions on Sentry in the testing phase is better than having a chance of missing them. Afterward, they can read the docs and/or directly adjust the value. Wdyt?

2021-05-31 11:08 UTC, AbhiPrasad requested changes
As per slack discussion, can we include some kind of messaging after install to indicate that tracing is turned on with 100% sample rate. Maybe include docs to performance monitoring docs to show users how to upgrade their plan if needed.

2021-05-31 12:13 UTC, AbhiPrasad approved these changes

2021-05-31 12:21 UTC, merged