fix(remix): Change `handleError` in server entry
getsentry/sentry-wizard pull request #621
Opened 2024-07-08 08:52 UTC by s1gr1d

Changes the produced code for `handleError` based on the docs.

docs PR: https://github.com/getsentry/sentry-docs/pull/10597
related issue: https://github.com/getsentry/sentry-javascript/issues/12785

2024-07-08 09:49 UTC, onurtemizkan requested changes

2024-07-08 09:49 UTC, onurtemizkan commented on src/remix/templates.ts
> +export const HANDLE_ERROR_TEMPLATE_V2 = `export const handleError = Sentry.wrapHandleErrorWithSentry((error, { request }) => {
This generated the code below in my test app:

```
export export const handleError = Sentry.wrapHandleErrorWithSentry((error, { request }) => {
  // Custom handleError implementation
});
```

We should remove the logic that:

- `exports` the code in the template - [handle-error.ts
](https://github.com/getsentry/sentry-wizard/pull/621/files#diff-f2d0582b002c65e3ca8edfda1037ef827a172db2ba6f879b5d1d9abb42bfbf87R48)
- Or we can remove `export` from the template instead.

2024-07-09 16:10 UTC, onurtemizkan commented
@s1gr1d - I updated the codemod to work on the new template.

2024-07-09 19:19 UTC, s1gr1d commented
Looks good! Feel free to merge it after you accept it. I cannot accept as I opened the PR.

2024-07-10 10:31 UTC, onurtemizkan approved these changes

2024-07-10 10:31 UTC, merged